MB-60861: Include the conversions header from json_log.h
The conversions should be available without requiring an #include.
Users should just include json_log.h.

Also, since the conversions header contains template specialisations,
having cases where it is not included can result in compiler error:

  error: partial specialization of ... after instantiation of
    cb::logger::JsonSerializer

Change-Id: Ie77ce7328d05f1f40b360b4d2c5ef48d1a4f30d9
Reviewed-on: https://review.couchbase.org/c/platform/+/221690
Tested-by: Build Bot <build@couchbase.com>
Reviewed-by: Trond Norbye <trond.norbye@couchbase.com>