MB-41209: Fixes for upgrading to Folly v2020.08.24.00
1. Use the socket-related portability types from Folly instead of
defining them outselves.

This both avoids duplication of a bunch of fiddly platform-specific
code, and also addresses conflicts if both platform and Folly try to
define the same types - as seen when building on Windows with latest
Folly:

    build\tlm\deps\folly.exploded\include\folly/portability/IOVec.h(28): warning C4005: 'IOV_MAX': macro redefinition
    platform\include\platform/platform_socket.h(43): note: see previous definition of 'IOV_MAX'
    build\tlm\deps\folly.exploded\include\folly/portability/IOVec.h(30): error C2011: 'iovec': 'struct' type redefinition
    platform\include\platform/platform_socket.h(38): note: see declaration of 'iovec'
    build\tlm\deps\folly.exploded\include\folly/net/NetOps.h(104): error C2371: 'sa_family_t': redefinition; different basic types
    platform\include\platform/socket.h(32): note: see declaration of 'sa_family_t'
    build\tlm\deps\folly.exploded\include\folly/net/NetOps.h(118): error C2011: 'msghdr': 'struct' type redefinition
    platform\include\platform/platform_socket.h(45): note: see declaration of 'msghdr'
    build\tlm\deps\folly.exploded\include\folly/net/NetOps.h(129): error C2079: 'mmsghdr::msg_hdr' uses undefined struct 'msghdr'
    build\tlm\deps\folly.exploded\include\folly/io/async/EventBaseBackendBase.h(36): error C2079: 'folly::EventReadCallback::IoVec::data_' uses undefined struct 'iovec'
    build\tlm\deps\folly.exploded\include\folly/io/async/EventBaseBackendBase.h(54): error C2079: 'folly::EventRecvmsgCallback::MsgHdr::data_' uses undefined struct 'msghdr'

2. Define a non-zero initial cpuCount for corestore_test, to avoid an
infinite loop with latest Folly.

Change-Id: If5a5a906c4c67fe6781eb0ea201ac16ad1deedbd
Reviewed-on: http://review.couchbase.org/c/platform/+/135926
Tested-by: Build Bot <build@couchbase.com>
Reviewed-by: Trond Norbye <trond.norbye@couchbase.com>