RelaxedAtomic: Remove 'explicit' definition for copy constructor
Removing explicit as windows complains when using RelaxedAtomic inside
an STL container:

    C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\vector(1708) :
    error C2558:
    class 'Couchbase::RelaxedAtomic<uint64_t>' : no copy constructor available or copy constructor is declared 'explicit')

Change-Id: I5c03348a720c28448b762a802a3c9b3fd282af14
Reviewed-on: http://review.couchbase.org/55889
Tested-by: buildbot <build@couchbase.com>
Reviewed-by: Dave Rigby <daver@couchbase.com>