Revert "Add cb::make_array"
Breaks under Centos6 / Centos7 (GCC 4.?): http://server.jenkins.couchbase.com/job/couchbase-server-unix/39032/

platform/tests/make_array/make_array_test.cc>:31:196: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
    EXPECT_EQ("Couchbase"_ccb, string_array.at(2));
                                                                                                                    ^
platform/tests/make_array/make_array_test.cc: In member function 'virtual void MakeArrayTest_Basic_Test::TestBody()':
platform/tests/make_array/make_array_test.cc:31:198: error: expected ')' before 'Couchbase'
    EXPECT_EQ("Couchbase"_ccb, string_array.at(2));

This reverts commit 678b006eb33128ff8cca92adb173d7f9e5d8b3c7.

Change-Id: I448a4cb178c1da27ce32bc3e48f33074eac3dd90
Reviewed-on: http://review.couchbase.org/79815
Tested-by: Build Bot <build@couchbase.com>
Reviewed-by: Dave Rigby <daver@couchbase.com>