NonNegativeCounter: make copy-ctor non-explicit
GCC 5.4 appears to have a bug where it fails to inline the call to a
copy constructor of the templated type for std::array in some
circumstances (not totally clear). More specifically, we see a linker
failure in kv_engine/hash_table_test.cc (after some refactoring) when
generating code to copy a std::array<NonNegativeCounter> for the
following code:

    HashTable ht;
    auto datatypeCountsBeforeCopy = ht.datatypeCounts;

where datatypeCounts is of type:

    std::array<cb::NonNegativeCounter<size_t>,
               mcbp::datatype::highest + 1>

This results in the following error:

    hash_table_test.cc.o: In function `std::array<cb::NonNegativeCounter<unsigned long, cb::ClampAtZeroUnderflowPolicy>, 8ul>::array(std::array<cb::NonNegativeCounter<unsigned long, cb::ClampAtZeroUnderflowPolicy>, 8ul> const&)':
    /usr/include/c++/5/array:89: undefined reference to `cb::NonNegativeCounter<unsigned long, cb::ClampAtZeroUnderflowPolicy>::NonNegativeCounter(unsigned long)'
    collect2: error: ld returned 1 exit status

The code compiles fine in clang & MSVC.

I don't know the exact root cause here, but removing the `explicit`
keyword from NonNegativeCounter's copy-ctor avoid the problem. Given
the argument to the constructor is simply read from (via load()); I
don't think removing explicit will cause any other issues.

Change-Id: Ic6cdd8327444fde09cd18de71862a86f2ad67cef
Reviewed-on: http://review.couchbase.org/87467
Tested-by: Build Bot <build@couchbase.com>
Reviewed-by: Daniel Owen <owend@couchbase.com>